### PR TITLE
Double-click to edit the current selection

### PR DESCRIPTION
**Pull request by eevee**
Seems useful, and the notion of a double click doesn't make much sense to the keybind system.

### CODE REVIEW

**Comment by sirjuddington** [comment]
Might be an idea to put this one behind a config (can be enabled by default)

**Comment by eevee** [comment]
Sure, if you want, though I'm wary of ending up with checkbox overload — this seemed safe since currently double-click is only interpreted as two clicks, which will toggle the selection of whatever you're pointing at twice, i.e. do absolutely nothing.

**Comment by sirjuddington** [comment]
I was more worried about people accidentally invoking it, I'm not too concerned about having too many options :P

**Comment by eevee** [comment]
Pref added, under the "click nothing to clear selection" pref.

**Pull request merged**
