### PR TITLE
Map editor 3d floors support in 3d mode

### PR DESCRIPTION
**Pull request by sirjuddington**
This is an adaptation of #966 to work with the current code base. All of the WIPs/issues in @eevee's comment there still apply.

From the small amount of testing I have done so far, it seems to work ok enough for basic, solid 3d floors at least. Swimmable/transparent 3d floors have quite a few bugs on the other hand, not sure if I've introduced them during the adaptation process or if they were there in the old branch.

So yeah this definitely isn't ready for a proper release just yet, and likely needs a bunch of work to get up to scratch. I've added a cvar to enable/disable 3d floors processing so it could potentially be released as an 'experimental' feature that is off by default or something.

And of course if anyone wants to have a go at fixing all the issues with it and/or adding the missing features, feel free :P

### CODE REVIEW

**Comment by OrdinaryMagician** [comment]
Any chance of this ever making it in?

**Comment by sirjuddington** [comment]
> Any chance of this ever making it in?

Hmm well I doubt it will be finished (ie. all bugs fixed) any time soon, but as I mentioned in the description I guess it could be added as-is but disabled by default, with a warning that it's incomplete/buggy when enabling it.

**Comment by wallabra** [comment]
Would it be better to have this as a draft?

**Comment by Pedro-Beirao** [comment]
Since this PR, the 3d mode crashes on macOS. Even with 3d floors disabled

I'll try to find the problem tomorrow, but here's the crash if you know how to fix

```
slade(31963,0x1e3c81300) malloc: Heap corruption detected, free list is damaged at 0x600002c3be50
*** Incorrect guard value: 105553134610992
slade(31963,0x1e3c81300) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Pull request merged**
