### PR TITLE
Make SLADE's map editor recognize full path textures.

### PR DESCRIPTION
**Pull request by Talon1024**
I've modified the resource manager code so that walls and flats in a UDMF-format map that use the full path name of an image file from a ZIP/PK3 archive as a texture name (you'll find countless examples in WolfenDoom: Blade of Agony) will be recognized and loaded by SLADE's map editor.

### CODE REVIEW

**Comment by sirjuddington** [comment]
Haven't had a chance to try this out yet, but just a minor thing with the formatting - the SLADE source has opening braces `{` on the next line, not the same line as you have here

**Comment by Talon1024** [comment]
OK, I changed the code style of my additions, and I removed some extra code (trimmed entry names) because I'm not sure that code belongs there.

Also, could this feature be added to the stable version of SLADE as well?

**Comment by sirjuddington** [comment]
If you want it in stable you'll need to create a new pull request to apply to stable instead of master.

**Comment by eevee** [comment]
Whoa, I didn't even know this was possible; I'd looked for mentions of it on the ZDoom wiki before, but only found vague mention that "in the future" paths will maybe be supported somehow.

Does this imply that it should be possible to select textures by path, somehow?  At least if their names are longer than 8 characters.

**Comment by Talon1024** [comment]
> Does this imply that it should be possible to select textures by path, somehow? At least if their names are longer than 8 characters.

I think SLADE already uses textures with names longer than 8 characters. Load up C1Train from WolfenDoom: Blade of Agony, and you'll see a few missing textures, despite the fact that those texture names are only 8 characters long. This is because the PNG files corresponding to those textures have "basenames" longer than 8 characters.

On the other hand, I think users should have the option of whether or not to use full path texture names, except in the case where you have two textures with the same filename, but in different folders within the PK3.

**Comment by Talon1024** [comment]
Heya. Is there anything else I need to do before this gets merged?

**Comment by sirjuddington** [comment]
Oh, well yeah it works fine, I thought you wanted to swap it over to stable though?

**Comment by Talon1024** [comment]
I've changed my mind. It looks to me like there won't be many more changes to the stable branch before the next version comes out.

**Comment by sirjuddington** [comment]
The stable branch is actually still active, and there will definitely be more 3.1.1.x builds before 3.1.2 is ready (it's still a ways off).

So I think this is actually better for stable as a temporary fix for now. As it is, even with this fix, UDMF full path textures aren't really supported properly (they display, but don't work correctly in other places such as the browser). Adding full support will probably require a bit of a rework in how SLADE handles textures, which would be for 3.1.2 or 3.1.3.

**Pull request closed without merging**
