### PR TITLE
Some updates from my branch

### PR DESCRIPTION
**Pull request by Gaerzi**
Some preliminary stuff so I can deconflict and port the rest of the music branch.

### CODE REVIEW

**Comment by sirjuddington** [comment]
Hmm I can't build this (with the fixes also) because my fluidsynth doesn't have fluid_player_add_mem. Is there a newer precompiled lib/dll for fluidsynth than 1.1.3?

**Comment by Gaerzi** [comment]
The [fluidsynth lib from ZDoom](http://www.zdoom.org/files/fluidsynth.7z) should work.

**Comment by sirjuddington** [comment]
What .libs are you using, is it easier to build them now with the gtk stuff statically linked?

**Comment by Gaerzi** [comment]
[Here's the lib I built](https://anonfiles.com/file/e07df07e4627bfd7b2048805689af92e) long ago.

**Pull request merged**
