### PR TITLE
Small bugfix

### PR DESCRIPTION
**Pull request by Monsterovich**
https://github.com/sirjuddington/SLADE/pull/325

### CODE REVIEW

**Comment by eevee** [comment]
Well that's bizarre.  It works fine here; a double-click fires both events.

**Comment by Monsterovich** [comment]
No, it doesn't. http://www.youtube.com/watch?v=_SukzbM0xiI

**Comment by eevee** [comment]
I assure you the same sequence of events had different results for me  :)  Which is even all the more strange given that we both seem to be using wxGTK.

**Comment by Monsterovich** [comment]
>a double-click fires both events.
I hope you know that only onSpecialItemActivated has a double-click trigger. I had these lines for it, but you returned onSpecialItemChanged by renaming onSpecialItemActivated (this is done right) and moved onSpecialItemActivated. I just want to mention that onSpecialItemChanged works only when you switch your selection from one item to another, so it doesn't work when you click any item first time. (see video)

**Comment by eevee** [comment]
Oh, wait, I see; I didn't realize you'd _typed_ the first special in your video.

**Pull request merged**
