### PR TITLE
New palettes

### PR DESCRIPTION
**Pull request by Ozymandias81**
PALETTES:
:new: Added 48 new palettes and renamed UrbanBrawl.pal into Urban
Brawl.pal

Here you are a list of these new palettes:

:arrow_forward: Chasm: The Rift
:arrow_forward: Descent I & II
:arrow_forward: 8 different Doom projects
:arrow_forward: Dungeon Hack
:arrow_forward: Dungeon Master I & II
:arrow_forward: Elidor
:arrow_forward: Eradicator
:arrow_forward: Elder Scrolls I & II
:arrow_forward: Eye of the Beholder I & III
:arrow_forward: In Pursuit of Greed
:arrow_forward: Laser Arena
:arrow_forward: MDK I
:arrow_forward: N.A.M.: Napalm
:arrow_forward: Necrodome
:arrow_forward: Powerslave / Exhumed
:arrow_forward: Quiver
:arrow_forward: Realms of the Haunting
:arrow_forward: Resident Evil I
:arrow_forward: (Adventures of) Square
:arrow_forward: System Shock I & II
:arrow_forward: World of Aden: Thunderscape
:arrow_forward: Ultima Underworld I & II
:arrow_forward: Witchaven I & II
:arrow_forward: World War II: G.I.

### CODE REVIEW

**Comment by Ozymandias81** [comment]
Ok, so it seems this pull request is fine then. :tongue:

**Comment by Gaerzi** [comment]
Can SLADE actually open the data files for most of these? Also I'm not sure all of these palettes work. For example the Laser Arena is in JASC format, which SLADE does not use natively (even if it can import from it). There are a couple of other palettes (Arena Dreary and Realm of the Haunting) which GitHub previews as text files. Have you checked they all work correctly?

**Comment by Ozymandias81** [comment]
Yeah, those works... Probably only the Dreary doesn't work correctly

Alien Arena 
image

Arena Dreary
image

Realms of the Haunting
image

**Comment by Ozymandias81** [comment]
I'll see if I can provied a test for all related data files within such palettes.
Surely several of them can't be opened by Slade, that was very old / aged stuff that I managed to extarct with xWe many years ago so far.

**Comment by Ozymandias81** [comment]
OK, let's get to the point concerning resource which can be opened with Slade:

**CHASM: THE RIFT**
CSM.BIN file contains quite all resources from the game and it can be opened with Slade
image, but for .CEL sprites / textures I used xWe to scout... and I noticed that they are .bmp files... 
image

**Comment by Ozymandias81** [comment]
**WORLD OF ADEN: THUNDERSCAPE**
THUNDER.DAT is the main resource file and it can be opened with Slade 
image
 and the graphics are so dark because of embedded palettes within the .dat file...
Then I noticed that if I de-select
image
 Thunderscape palettes from Slade, graphics
image
 are displayed correctly...
How to rework the palette then? Is it ever possible to merge genpal + pal1-5 palettes into a single one?

**Comment by Ozymandias81** [comment]
**DUNGEON HACK**
HACK.RES & OPEN.RES are the main resource files from the game, but Slade can't open them unfortunately...
I managed to rip the palette with xWe back in the days, so here you are an example: 
image
Could be possible in the future to make Slade open .RES or .REZ files?

**Comment by Gaerzi** [comment]
For the Thunderscape sprites being dark, this is probably because the palette is 6-bit instead of 8-bit (meaning the brightest color channel value is 63 instead of 255). SLADE 3 can detect this kind of palette by the lack of any color value at 64 or above; you can also use the palconv console command while the palette is selected to make it 8-bit.

As for adding new archive formats, sure, it's possible, but it's a question of time, motivation, and the availability of specs. Suffice to say it's generally low priority.

**Comment by Ozymandias81** [comment]
The PALCONV suggestion fixed
image
 the issue with the brightness 
image, thanks a lot!

Concerning the new archive formats suppor thing I understand np by my side.

**Comment by Ozymandias81** [comment]
Consider this close for now, I am pretty busy with everything and probably I'll have only some spare time this summer. :sob:

**Pull request closed without merging**
